version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: myapp_development
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    # MySQL8.0からセキュリティが強化されたようで、--default-authentication-plugin=mysql_native_password を実行して認証方式を mysql_native_password へ変更する必要があり
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      RAILS_DB_HOST: db # データベースコンテナ名と一致させる
      RAILS_DB_NAME: myapp_development # MYSQL_DATABASEと一致させる
      RAILS_DB_USER: user # MYSQL_USERと一致させる
      RAILS_DB_PASSWORD: root # MYSQL_PASSWORDと一致させる
      RAILS_ENV: development
      RAILS_HOST_URL: http://localhost:3000
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      NODE_OPTIONS: '--openssl-legacy-provider'
      NUXT_ENV_RAILS_URL: http://localhost:3000
      FIREBASE_API_KEY: $FIREBASE_API_KEY
      FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
      FIREBASE_DATABASE_URL: $FIREBASE_DATABASE_URL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
      FIREBASE_MESSSAGE_SENDER_ID: $FIREBASE_MESSSAGE_SENDER_ID
      FIREBASE_APP_ID: $FIREBASE_APP_ID
      FIREBASE_MEASUREMENT_ID: $FIREBASE_MEASUREMENT_ID
    command: yarn dev
#    volumes:
#      - ./frontend:/frontend