version: "3"
volumes:
  frontend:
    driver: 'local'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: myapp_development
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    command: '--default-authentication-plugin=mysql_native_password'
    #MySQL8.0からセキュリティが強化されたようで、--default-authentication-plugin=mysql_native_password を実行して認証方式を mysql_native_password へ変更する必要があり
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - frontend:/myapp/frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      RAILS_DB_HOST: db # データベースコンテナ名と一致させる
      RAILS_DB_NAME: myapp_development # MYSQL_DATABASEと一致させる
      RAILS_DB_USER: user # MYSQL_USERと一致させる
      RAILS_DB_PASSWORD: root # MYSQL_PASSWORDと一致させる
      RAILS_ENV: development
      RAILS_HOST_URL: localhost:3000
  # ここから追加
  frontend:
    build: ./frontend
    tty: true
    ports:
      - 80:80
    environment:
      NODE_OPTIONS: '--openssl-legacy-provider'
    command: bash -c "yarn dev"
    volumes:
      - ./frontend:/frontend